### ISSUE TITLE
Status or alternatives

### ISSUE THREAD

**Issue by paulocoghi** [nicbet/cart#1]
Hi Nicolas!

I would like to ask if you plan to finish the library or if you found an alternative one, like a C bind for crystal.

Thanks!

**Comment by nicbet** [comment]
Hi @paulocoghi, haven't looked at this in a very long time - mostly because Crystal pre 1.0 had a number of breaking API changes ;-) 

I think today, your best bet would be to take a reference implementation in C and write your own Crystal bindings to the C code. 

A full Crystal implementation could be a fun project as well, now that Pointers and Types are fairly stable. Take a look at https://db.in.tum.de/~leis/papers/ART.pdf for the core pseudo-code.

**Comment by paulocoghi** [comment]
Thanks for the kind response! Probably I will go with https://github.com/armon/libart

**Comment by nicbet** [comment]
So I've been having some fun with Crystal the past few days and started a first rough down on what ART would look like in Crystal-native. Currently only supports Leaf nodes and Node4 types but proofs the point ;-). @paulocoghi

**Comment by paulocoghi** [comment]
Wow! Thanks a lot for the excellent example!
